### ISSUE TITLE
Fails to build on Gentoo with Clang and Glibc 2.43

### ISSUE THREAD

**Issue by theoparis** [jamienicol/glslopt-rs#12]
This seems to be causing the servo browser to fail to compile:
```
  cargo:warning=In file included from glsl-optimizer/include/c11/threads.h:66,
  cargo:warning=                 from glsl-optimizer/src/mesa/main/mtypes.h:39,
  cargo:warning=                 from src/compiler/glsl/glcpp/glcpp-parse.y:32:
  cargo:warning=glsl-optimizer/include/c11/threads_posix.h:69:25: error: conflicting types for 'once_flag'; have 'pthread_once_t' {aka 'int'}
  cargo:warning=   69 | typedef pthread_once_t  once_flag;
  cargo:warning=      |                         ^~~~~~~~~
  cargo:warning=In file included from /usr/include/stdlib.h:1191,
  cargo:warning=                 from src/compiler/glsl/glcpp/glcpp-parse.y:26:
  cargo:warning=/usr/include/bits/types/once_flag.h:24:21: note: previous declaration of 'once_flag' with type 'once_flag'
  cargo:warning=   24 | typedef __once_flag once_flag;
  cargo:warning=      |                     ^~~~~~~~~
  cargo:warning=glsl-optimizer/include/c11/threads_posix.h:94:1: error: conflicting types for 'call_once'; have 'void(int *, void (*)(void))'
  cargo:warning=   94 | call_once(once_flag *flag, void (*func)(void))
  cargo:warning=      | ^~~~~~~~~
  cargo:warning=/usr/include/stdlib.h:1195:13: note: previous declaration of 'call_once' with type 'void(once_flag *, void (*)(void))'
  cargo:warning= 1195 | extern void call_once (once_flag *__flag, void (*__func)(void));
  cargo:warning=      |             ^~~~~~~~~
  cargo:warning=In file included from glsl-optimizer/include/c11/threads.h:66,
  cargo:warning=                 from glsl-optimizer/src/mesa/main/mtypes.h:39,
  cargo:warning=                 from glsl-optimizer/src/compiler/glsl/glcpp/pp_standalone_scaffolding.h:34,
  cargo:warning=                 from glsl-optimizer/src/compiler/glsl/glcpp/pp_standalone_scaffolding.c:30:
  cargo:warning=glsl-optimizer/include/c11/threads_posix.h:69:25: error: conflicting types for 'once_flag'; have 'pthread_once_t' {aka 'int'}
  cargo:warning=   69 | typedef pthread_once_t  once_flag;
  cargo:warning=      |                         ^~~~~~~~~
  cargo:warning=In file included from /usr/include/stdlib.h:1191,
  cargo:warning=                 from glsl-optimizer/include/c11/threads_posix.h:29:
  cargo:warning=/usr/include/bits/types/once_flag.h:24:21: note: previous declaration of 'once_flag' with type 'once_flag'
  cargo:warning=   24 | typedef __once_flag once_flag;
  cargo:warning=      |                     ^~~~~~~~~
  cargo:warning=glsl-optimizer/include/c11/threads_posix.h:94:1: error: conflicting types for 'call_once'; have 'void(int *, void (*)(void))'
  cargo:warning=   94 | call_once(once_flag *flag, void (*func)(void))
  cargo:warning=      | ^~~~~~~~~
  cargo:warning=/usr/include/stdlib.h:1195:13: note: previous declaration of 'call_once' with type 'void(once_flag *, void (*)(void))'
  cargo:warning= 1195 | extern void call_once (once_flag *__flag, void (*__func)(void));
  cargo:warning=      |             ^~~~~~~~~
  cargo:warning=In file included from glsl-optimizer/include/c11/threads.h:66,
  cargo:warning=                 from glsl-optimizer/src/mesa/main/mtypes.h:39,
  cargo:warning=                 from glsl-optimizer/src/compiler/glsl/glcpp/pp.c:28:
  cargo:warning=glsl-optimizer/include/c11/threads_posix.h:69:25: error: conflicting types for 'once_flag'; have 'pthread_once_t' {aka 'int'}
  cargo:warning=   69 | typedef pthread_once_t  once_flag;
  cargo:warning=      |                         ^~~~~~~~~
  cargo:warning=In file included from /usr/include/stdlib.h:1191,
  cargo:warning=                 from glsl-optimizer/src/util/hash_table.h:31,
  cargo:warning=                 from glsl-optimizer/src/compiler/glsl/glcpp/glcpp.h:34,
  cargo:warning=                 from glsl-optimizer/src/compiler/glsl/glcpp/pp.c:27:
  cargo:warning=/usr/include/bits/types/once_flag.h:24:21: note: previous declaration of 'once_flag' with type 'once_flag'
  cargo:warning=   24 | typedef __once_flag once_flag;
  cargo:warning=      |                     ^~~~~~~~~
  cargo:warning=glsl-optimizer/include/c11/threads_posix.h:94:1: error: conflicting types for 'call_once'; have 'void(int *, void (*)(void))'
  cargo:warning=   94 | call_once(once_flag *flag, void (*func)(void))
  cargo:warning=      | ^~~~~~~~~
  cargo:warning=/usr/include/stdlib.h:1195:13: note: previous declaration of 'call_once' with type 'void(once_flag *, void (*)(void))'
  cargo:warning= 1195 | extern void call_once (once_flag *__flag, void (*__func)(void));
  cargo:warning=      |             ^~~~~~~~~
  exit status: 0
  exit status: 0
  exit status: 0
  exit status: 1
```

**Comment by whatifwevibed** [comment]
While attempting to build Librewolf on arch via the [AUR PKGBUILD,](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=librewolf) the following errors are produced from glslopt-rs:

     1:09.08 warning: glslopt@0.1.12: In file included from src/compiler/glsl/glcpp/glcpp-parse.y:32:
     1:09.09 warning: glslopt@0.1.12: In file included from glsl-optimizer/src/mesa/main/mtypes.h:39:
     1:09.09 warning: glslopt@0.1.12: In file included from glsl-optimizer/include/c11/threads.h:66:
     1:09.09 warning: glslopt@0.1.12: glsl-optimizer/include/c11/threads_posix.h:69:25: error: typedef redefinition with different types ('pthread_once_t' (aka 'int') vs '__once_flag')
     1:09.09 warning: glslopt@0.1.12:    69 | typedef pthread_once_t  once_flag;
     1:09.10 warning: glslopt@0.1.12:       |                         ^
     1:09.10 warning: glslopt@0.1.12: /usr/include/bits/types/once_flag.h:24:21: note: previous definition is here
     1:09.10 warning: glslopt@0.1.12:    24 | typedef __once_flag once_flag;
     1:09.10 warning: glslopt@0.1.12:       |                     ^
     1:09.11 warning: glslopt@0.1.12: In file included from src/compiler/glsl/glcpp/glcpp-parse.y:32:
     1:09.11 warning: glslopt@0.1.12: In file included from glsl-optimizer/src/mesa/main/mtypes.h:39:
     1:09.11 warning: glslopt@0.1.12: In file included from glsl-optimizer/include/c11/threads.h:66:
     1:09.12 warning: glslopt@0.1.12: glsl-optimizer/include/c11/threads_posix.h:94:1: error: static declaration of 'call_once' follows non-static declaration
     1:09.12 warning: glslopt@0.1.12:    94 | call_once(once_flag *flag, void (*func)(void))
     1:09.12 warning: glslopt@0.1.12:       | ^
     1:09.12 warning: glslopt@0.1.12: /usr/include/stdlib.h:1195:13: note: previous declaration is here
     1:09.13 warning: glslopt@0.1.12:  1195 | extern void call_once (once_flag *__flag, void (*__func)(void));
     1:09.13 warning: glslopt@0.1.12:       |             ^

I have limited info about the build environment not described in the PKGBUILD, but some basic stuff would be glibc v2.43+r5+g856c426a7534-1, rust v1:1.93.1-1, and llvm/clang/compiler-rt/lld v21.1.8-1.

The maintainers of the librewolf package on the AUR have recieved issue reports on this as well.

Thanks for all the hard work.

**Comment by alerque** [comment]
This started blocking builds of Servo on Arch Linux too :(

**Comment by xales** [comment]
The Arch `firefox` package has a patch around this failure: https://gitlab.archlinux.org/archlinux/packaging/packages/firefox/-/blob/6ecc647be2674a3c10c0c324ecd9833d303b3df8/0003-Patch-glsl-optimizer-to-build-with-glibc-2.43.patch

**Comment by xuhcc** [comment]
It has been fixed https://github.com/jamienicol/glslopt-rs/pull/14#issuecomment-4287215649
